plotitle: Aashutosh Aman Mishra
logo: display picture-circle.png
[[params.social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.co.in/citations?user=USERID"
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
