title: Aashutosh A Mishra
logo: display picture-circle.png
# description: text below image
Connect with me on:

[![LinkedIn](https://img.shields.io/badge/LinkedIn-0A66C2?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/mishra-aashutosh/)
[![Google Scholar](https://img.shields.io/badge/Google%20Scholar-4285F4?style=for-the-badge&logo=google-scholar&logoColor=white)](https://scholar.google.com/citations?user=m6qyYHgAAAAJ&hl=en)

# show_downloads: true
theme: jekyll-theme-minimal
